add vxlan support

diff --git a/bin/dl-join b/bin/dl-join
--- a/bin/dl-join
+++ b/bin/dl-join
@@ -3,7 +3,7 @@
 DIR_NAME=$(dirname $0)
 CUR_DIR=$(pwd)
 
-DEPENDS="rsync cgroup-lite lxc lxc-templates lxcfs bridge-utils curl sshfs squashfs-tools netcat-openbsd net-tools psmisc openssh-server" # criu openvswitch-switch
+DEPENDS="rsync cgroup-lite lxc lxc-templates lxcfs bridge-utils curl sshfs squashfs-tools netcat-openbsd net-tools psmisc openssh-server openvswitch-switch" # criu
 
 if ! dpkg -L ${DEPENDS} >/dev/null 2>&1; then apt-get install -y --no-install-recommends ${DEPENDS}; fi
 
@@ -19,7 +19,7 @@ function log_msg {
 }
 
 function get_address {
-	ADDRESS=`ip route | awk '{ if ($3=="'$(ip route | grep "^default via" | tail -n 1 | awk '{print $5}')'") print $9 }' | tail -n 1`
+	ADDRESS=`ip route | awk '{ if ($3=="'$(ip route | grep "^default via" | head -n 1 | awk '{print $5}')'") print $9 }' | tail -n 1`
 	echo ${ADDRESS:-10.10.0.1}
 	unset ADDRESS
 	# nmap -sP "${MACHINE_CIDR}" | grep report | awk '{print $NF}' | awk -F\( '{print $NF}' | awk -F\) '{print $1}'
@@ -27,9 +27,9 @@ function get_address {
 
 HOST_IP=$(get_address); if [[ "$@" == "network" ]]; then echo ${HOST_IP}; exit 0; fi
 
-grep swapaccount=1 /proc/cmdline >/dev/null || log_msg "ERROR" "Swap Account not enabled."
-
 log_msg "INFO" "IP of this host is ${HOST_IP}."
+
+grep swapaccount=1 /proc/cmdline >/dev/null || log_msg "ERROR" "Swap Account not enabled."
 
 log_msg "INFO" "Checking Environment for Docklet Cluster .."
 
@@ -48,7 +48,7 @@ ln -s /var/lib/docklet/global/machines/${HOST_IP} /var/run/netns
 touch /var/lib/docklet/global/docklet.conf
 . /var/lib/docklet/global/docklet.conf
 
-if [[ "${IP_DEV:-ovs-bridge}" == "ovs-bridge" ]]; then
+if [[ "${IP_DEV:-ovs-link}" == "ovs-link" ]]; then
 	log_msg "WARN" "Setting up for localhost."
 	
 	if [[ ! -e "/root/.ssh/id_rsa" ]] && [[ ! -e "/root/.ssh/authorized_keys" ]]; then
@@ -61,32 +61,39 @@ if [[ "${IP_DEV:-ovs-bridge}" == "ovs-bridge" ]]; then
 	fi
 	
 	ssh -oStrictHostKeyChecking=no root@0.0.0.0 true
-
-	if ! ip addr show ovs-bridge 2>/dev/null | grep 10.10.0.1 >/dev/null; then
-		iptables -F
-		iptables -t nat -F
+	
+	if ! ip addr show vxlan-int 2>/dev/null | grep 10.10.0.1 >/dev/null; then
+		#iptables -F
+		#iptables -t nat -F
+		iptables -t nat -D POSTROUTING -s 10.0.3.0/24 ! -d 10.0.3.0/24 -j MASQUERADE >/dev/null 2>&1 || true
+		iptables -t nat -D POSTROUTING -s 10.10.0.0/16 -j MASQUERADE >/dev/null 2>&1 || true
 		iptables -t nat -A POSTROUTING -s 10.10.0.0/16 -j MASQUERADE
 
 		ip link set ovs-link down 2>/dev/null || true
-		ip link set ovs-bridge down 2>/dev/null || true
+		# ip link set ovs-bridge down 2>/dev/null || true
 
-		brctl delbr ovs-bridge 2>/dev/null || true
-		brctl addbr ovs-bridge
+		# brctl delbr ovs-bridge 2>/dev/null || true
+		# brctl addbr ovs-bridge
 
-		# ovs-vsctl del-br ovs-link 2>/dev/null || true
-		# ovs-vsctl add-br ovs-link 2>/dev/null || true
-		# ip link set ovs-link up 2>/dev/null || true
+		ovs-vsctl del-br ovs-link 2>/dev/null || true
+		ovs-vsctl add-br ovs-link 2>/dev/null || true
 		# ovs-vsctl add-port ovs-link gre-${HOST} -- set interface gre-${HOST} type=gre options:remote_ip=${HOST}
-
 		sleep 2s
-		ip link set dev ovs-bridge up
-		ip addr add 10.10.0.1/16 dev ovs-bridge broadcast 10.10.255.255
-		brctl addif ovs-bridge ovs-link 2>/dev/null || true
+		
+		# brctl addif ovs-bridge ovs-link 2>/dev/null || true
+		ip addr add 10.10.0.1/16 dev ovs-link broadcast 10.10.255.255
+		
+		ip link set dev ovs-link up
+		ip link set dev ovs-system up
+
+		ip link add vxlan-int type vxlan id 41 group 239.10.0.1 local 192.168.1.200 dstport 0 >/dev/null 2>&1 || true
+		ip link set dev vxlan-int up
+		ovs-vsctl add-port ovs-link vxlan-int
 	fi
 	
 	kill -9 $(ps aux | grep dnsmasq | grep lxcbr0 | awk '{print $2}') >/dev/null 2>&1 || true
 	kill -9 $(ps aux | grep dnsmasq | grep 10.10 | awk '{print $2}') >/dev/null 2>&1 || true
-	dnsmasq -u lxc-dnsmasq --strict-order --bind-interfaces --pid-file=/run/lxc/dl-dnsmasq.pid --listen-address 10.10.0.1 --except-interface=lo --interface=ovs-bridge --dhcp-authoritative >/dev/null 2>&1 || true
+	dnsmasq -u lxc-dnsmasq --strict-order --bind-interfaces --pid-file=/run/lxc/dl-dnsmasq.pid --listen-address 10.10.0.1 --except-interface=lo --interface=ovs-link --dhcp-authoritative >/dev/null 2>&1 || true
 fi
 
 # log_msg "INFO" "Setting up for local LVM .."
